
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

#script: npm test && npm run build

deploy:
  provider: gae
  keyfile: mnemonipedia-gae-key.json
  project: mnemonipedia
  skip_cleanup: true
  on: master

before_deploy:
- openssl aes-256-cbc -K $encrypted_fd78d0a6e572_key -iv $encrypted_fd78d0a6e572_iv
  -in mnemonipedia-gae-key.json.enc -out mnemonipedia-gae-key.json -d
