
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

deploy:
  provider: gae
  keyfile: mnemonipedia-gae-key.json
  project: mnemonipedia
  on: production

before_install:
- openssl aes-256-cbc -K $encrypted_fd78d0a6e572_key -iv $encrypted_fd78d0a6e572_iv
  -in mnemonipedia-gae-key.json.enc -out mnemonipedia-gae-key.json -d

install:
  - gcloud config set project mnemonipedia
